[phases.setup]
nixPkgs = [
  "nodejs_22",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "fontconfig",
  "liberation_ttf"
]

[phases.install]
cmds = ["npm ci --omit=dev"]

[start]
cmd = "node src/index.js"